services:
  # 1. EL BACKEND
  - type: web
    name: wompi-backend
    env: node
    # Borramos la línea de plan aquí
    rootDir: wompi-backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wompi-db
          property: connectionString
      - key: PORT
        value: 10000

  # 2. EL FRONTEND
  - type: web
    name: wompi-frontend
    env: static
    # Borramos la línea de plan aquí
    rootDir: wompi-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://wompi-backend.onrender.com

databases:
  # 3. LA BASE DE DATOS
  - name: wompi-db
    plan: free # La base de datos sí requiere especificar el plan
    databaseName: wompi
    user: wompi